### ISSUE TITLE
Switch cache directory with a trait to allow other storage backends

### ISSUE THREAD

**Issue by ecton** [User65k/async-acme#3]
First off, thank you so much for this crate and for the quick merges on the pull requests I sent in last night.

I'm building a database which has its own encrypted-at-rest storage available, and I would like to be able to act as the account cache myself. I can manually manage the account and certificates if I drive the process by hand, but I can't use the `rustls_helper::order` function because that function returns a `CertifiedKey` which cannot be used to export the private key.

I propose changing the order function to take a trait implementation rather than a Path for the cache, with function calls to load and save accounts and certificates with their keys. The crate can continue to provide a filesystem implementation.

Would you be open to a pull request for this change?

**Comment by User65k** [comment]
Hi, thanks for contributing!

Yes, that sounds like a good way to deal with it.
A default implementation of the Trait on `AsRef<Path>` or Path could preserve the current behavior.

I created the `rustls_helper::drive_order` function just to be able to handle the cert storage myself but I am not to happy with that approach.
So this is actually very welcome.
