### ISSUE TITLE
async-std not working on main

### ISSUE THREAD

**Issue by ecton** [User65k/async-acme#4]
Because async-rustls is currently on rustls 0.19, there are errors when building the example. I found an open issue on that repository, which links to another thread on another project where someone mentions that [`futures-rustls`](https://crates.io/crates/futures-rustls) is preferred.

Should we change this project over, or should we wait on async-rustls to be updated?

**Comment by User65k** [comment]
That is actually why I did not push the last changes to crates.io.
I suppose we could swap it in.
I will do the same for the `generic-async-http-client` (dependency)

**Comment by User65k** [comment]
fixed in 4084757
